/* 
 * WebAPI
 *
 * Access Sponge powered Minecraft servers through a WebAPI  # Introduction This is the documentation of the various API routes offered by the WebAPI plugin.  This documentation assumes that you are familiar with the basic concepts of Web API's, such as `GET`, `PUT`, `POST` and `DELETE` methods, request `HEADERS` and `RESPONSE CODES` and `JSON` data.  By default this documentation can be found at http:/localhost:8080 (while your minecraft server is running) and the various routes start with http:/localhost:8080/api/...  As a quick test try reaching the route http:/localhost:8080/api/info (remember that you can only access \"localhost\" routes on the server on which you are running minecraft). This route should show you basic information about your server, like the motd and player count.  # Additional data Certain endpoints (such as `/player`, `/entity` and `/tile-entity` have additional properties which are not documented here, because the data depends on the concrete object type (eg. `Sheep` have a wool color, others do not) and on the other plugins/mods that are running on your server which might add additional data.  You can also find more information in the github docs (https:/github.com/Valandur/Web-API/tree/master/docs/DATA.md) 
 *
 * OpenAPI spec version: <version>
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BlockApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class BlockApiTests
    {
        private BlockApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new BlockApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BlockApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' BlockApi
            //Assert.IsInstanceOfType(typeof(BlockApi), instance, "instance is a BlockApi");
        }

        
        /// <summary>
        /// Test CancelBlockOperation
        /// </summary>
        [Test]
        public void CancelBlockOperationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string uuid = null;
            //var response = instance.CancelBlockOperation(uuid);
            //Assert.IsInstanceOf<BlockOperationResponse> (response, "response is BlockOperationResponse");
        }
        
        /// <summary>
        /// Test ChangeBlockOperation
        /// </summary>
        [Test]
        public void ChangeBlockOperationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string uuid = null;
            //Data data = null;
            //var response = instance.ChangeBlockOperation(uuid, data);
            //Assert.IsInstanceOf<BlockOperationResponse> (response, "response is BlockOperationResponse");
        }
        
        /// <summary>
        /// Test GetBlock
        /// </summary>
        [Test]
        public void GetBlockTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string world = null;
            //int? x = null;
            //int? y = null;
            //int? z = null;
            //var response = instance.GetBlock(world, x, y, z);
            //Assert.IsInstanceOf<SingleBlock> (response, "response is SingleBlock");
        }
        
        /// <summary>
        /// Test GetBlockOperation
        /// </summary>
        [Test]
        public void GetBlockOperationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string uuid = null;
            //var response = instance.GetBlockOperation(uuid);
            //Assert.IsInstanceOf<BlockOperationResponse> (response, "response is BlockOperationResponse");
        }
        
        /// <summary>
        /// Test GetBlockOperations
        /// </summary>
        [Test]
        public void GetBlockOperationsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetBlockOperations();
            //Assert.IsInstanceOf<BlockOperationsList> (response, "response is BlockOperationsList");
        }
        
        /// <summary>
        /// Test StartBlockOperation
        /// </summary>
        [Test]
        public void StartBlockOperationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<BlockOperationNew> request = null;
            //var response = instance.StartBlockOperation(request);
            //Assert.IsInstanceOf<BlockOperationResponse> (response, "response is BlockOperationResponse");
        }
        
    }

}
