/* 
 * WebAPI
 *
 * Access Sponge powered Minecraft servers through a WebAPI  # Introduction This is the documentation of the various API routes offered by the WebAPI plugin.  This documentation assumes that you are familiar with the basic concepts of Web API's, such as `GET`, `PUT`, `POST` and `DELETE` methods, request `HEADERS` and `RESPONSE CODES` and `JSON` data.  By default this documentation can be found at http:/localhost:8080 (while your minecraft server is running) and the various routes start with http:/localhost:8080/api/...  As a quick test try reaching the route http:/localhost:8080/api/info (remember that you can only access \"localhost\" routes on the server on which you are running minecraft). This route should show you basic information about your server, like the motd and player count.  # Additional data Certain endpoints (such as `/player`, `/entity` and `/tile-entity` have additional properties which are not documented here, because the data depends on the concrete object type (eg. `Sheep` have a wool color, others do not) and on the other plugins/mods that are running on your server which might add additional data.  You can also find more information in the github docs (https:/github.com/Valandur/Web-API/tree/master/docs/DATA.md) 
 *
 * OpenAPI spec version: <version>
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing EntityApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class EntityApiTests
    {
        private EntityApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new EntityApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EntityApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' EntityApi
            //Assert.IsInstanceOfType(typeof(EntityApi), instance, "instance is a EntityApi");
        }

        
        /// <summary>
        /// Test ChangeEntity
        /// </summary>
        [Test]
        public void ChangeEntityTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string uuid = null;
            //UpdateEntityRequest updateEntityRequest = null;
            //var response = instance.ChangeEntity(uuid, updateEntityRequest);
            //Assert.IsInstanceOf<EntityResponse> (response, "response is EntityResponse");
        }
        
        /// <summary>
        /// Test CreateEntity
        /// </summary>
        [Test]
        public void CreateEntityTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateEntityRequest createEntityRequest = null;
            //var response = instance.CreateEntity(createEntityRequest);
            //Assert.IsInstanceOf<EntityResponse> (response, "response is EntityResponse");
        }
        
        /// <summary>
        /// Test DestroyEntity
        /// </summary>
        [Test]
        public void DestroyEntityTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string uuid = null;
            //var response = instance.DestroyEntity(uuid);
            //Assert.IsInstanceOf<EntityResponse> (response, "response is EntityResponse");
        }
        
        /// <summary>
        /// Test ExecuteEntityMethod
        /// </summary>
        [Test]
        public void ExecuteEntityMethodTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string uuid = null;
            //RawRequest request = null;
            //var response = instance.ExecuteEntityMethod(uuid, request);
            //Assert.IsInstanceOf<EntityMethodResult> (response, "response is EntityMethodResult");
        }
        
        /// <summary>
        /// Test GetEntities
        /// </summary>
        [Test]
        public void GetEntitiesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string details = null;
            //var response = instance.GetEntities(details);
            //Assert.IsInstanceOf<EntitiesList> (response, "response is EntitiesList");
        }
        
        /// <summary>
        /// Test GetEntity
        /// </summary>
        [Test]
        public void GetEntityTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string uuid = null;
            //string fields = null;
            //string methods = null;
            //var response = instance.GetEntity(uuid, fields, methods);
            //Assert.IsInstanceOf<EntityResponse> (response, "response is EntityResponse");
        }
        
    }

}
