/* 
 * WebAPI
 *
 * Access Sponge powered Minecraft servers through a WebAPI  # Introduction This is the documentation of the various API routes offered by the WebAPI plugin.  This documentation assumes that you are familiar with the basic concepts of Web API's, such as `GET`, `PUT`, `POST` and `DELETE` methods, request `HEADERS` and `RESPONSE CODES` and `JSON` data.  By default this documentation can be found at http:/localhost:8080 (while your minecraft server is running) and the various routes start with http:/localhost:8080/api/...  As a quick test try reaching the route http:/localhost:8080/api/info (remember that you can only access \"localhost\" routes on the server on which you are running minecraft). This route should show you basic information about your server, like the motd and player count.  # Additional data Certain endpoints (such as `/player`, `/entity` and `/tile-entity` have additional properties which are not documented here, because the data depends on the concrete object type (eg. `Sheep` have a wool color, others do not) and on the other plugins/mods that are running on your server which might add additional data.  You can also find more information in the github docs (https:/github.com/Valandur/Web-API/tree/master/docs/DATA.md) 
 *
 * OpenAPI spec version: <version>
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// CommandResult
    /// </summary>
    [DataContract]
    public partial class CommandResult :  IEquatable<CommandResult>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CommandResult" /> class.
        /// </summary>
        /// <param name="AffectedBlocks">The number of block that were affected..</param>
        /// <param name="AffectedEntities">The number of entities that were affected..</param>
        /// <param name="AffectedItems">The number of items that were affected..</param>
        /// <param name="QueryResult">The query result number..</param>
        /// <param name="SuccessCount">The success count..</param>
        public CommandResult(decimal? AffectedBlocks = default(decimal?), decimal? AffectedEntities = default(decimal?), decimal? AffectedItems = default(decimal?), decimal? QueryResult = default(decimal?), decimal? SuccessCount = default(decimal?))
        {
            this.AffectedBlocks = AffectedBlocks;
            this.AffectedEntities = AffectedEntities;
            this.AffectedItems = AffectedItems;
            this.QueryResult = QueryResult;
            this.SuccessCount = SuccessCount;
        }
        
        /// <summary>
        /// The number of block that were affected.
        /// </summary>
        /// <value>The number of block that were affected.</value>
        [DataMember(Name="affectedBlocks", EmitDefaultValue=false)]
        public decimal? AffectedBlocks { get; set; }

        /// <summary>
        /// The number of entities that were affected.
        /// </summary>
        /// <value>The number of entities that were affected.</value>
        [DataMember(Name="affectedEntities", EmitDefaultValue=false)]
        public decimal? AffectedEntities { get; set; }

        /// <summary>
        /// The number of items that were affected.
        /// </summary>
        /// <value>The number of items that were affected.</value>
        [DataMember(Name="affectedItems", EmitDefaultValue=false)]
        public decimal? AffectedItems { get; set; }

        /// <summary>
        /// The query result number.
        /// </summary>
        /// <value>The query result number.</value>
        [DataMember(Name="queryResult", EmitDefaultValue=false)]
        public decimal? QueryResult { get; set; }

        /// <summary>
        /// The success count.
        /// </summary>
        /// <value>The success count.</value>
        [DataMember(Name="successCount", EmitDefaultValue=false)]
        public decimal? SuccessCount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CommandResult {\n");
            sb.Append("  AffectedBlocks: ").Append(AffectedBlocks).Append("\n");
            sb.Append("  AffectedEntities: ").Append(AffectedEntities).Append("\n");
            sb.Append("  AffectedItems: ").Append(AffectedItems).Append("\n");
            sb.Append("  QueryResult: ").Append(QueryResult).Append("\n");
            sb.Append("  SuccessCount: ").Append(SuccessCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as CommandResult);
        }

        /// <summary>
        /// Returns true if CommandResult instances are equal
        /// </summary>
        /// <param name="other">Instance of CommandResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CommandResult other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.AffectedBlocks == other.AffectedBlocks ||
                    this.AffectedBlocks != null &&
                    this.AffectedBlocks.Equals(other.AffectedBlocks)
                ) && 
                (
                    this.AffectedEntities == other.AffectedEntities ||
                    this.AffectedEntities != null &&
                    this.AffectedEntities.Equals(other.AffectedEntities)
                ) && 
                (
                    this.AffectedItems == other.AffectedItems ||
                    this.AffectedItems != null &&
                    this.AffectedItems.Equals(other.AffectedItems)
                ) && 
                (
                    this.QueryResult == other.QueryResult ||
                    this.QueryResult != null &&
                    this.QueryResult.Equals(other.QueryResult)
                ) && 
                (
                    this.SuccessCount == other.SuccessCount ||
                    this.SuccessCount != null &&
                    this.SuccessCount.Equals(other.SuccessCount)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.AffectedBlocks != null)
                    hash = hash * 59 + this.AffectedBlocks.GetHashCode();
                if (this.AffectedEntities != null)
                    hash = hash * 59 + this.AffectedEntities.GetHashCode();
                if (this.AffectedItems != null)
                    hash = hash * 59 + this.AffectedItems.GetHashCode();
                if (this.QueryResult != null)
                    hash = hash * 59 + this.QueryResult.GetHashCode();
                if (this.SuccessCount != null)
                    hash = hash * 59 + this.SuccessCount.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
