/* 
 * WebAPI
 *
 * Access Sponge powered Minecraft servers through a WebAPI  # Introduction This is the documentation of the various API routes offered by the WebAPI plugin.  This documentation assumes that you are familiar with the basic concepts of Web API's, such as `GET`, `PUT`, `POST` and `DELETE` methods, request `HEADERS` and `RESPONSE CODES` and `JSON` data.  By default this documentation can be found at http:/localhost:8080 (while your minecraft server is running) and the various routes start with http:/localhost:8080/api/...  As a quick test try reaching the route http:/localhost:8080/api/info (remember that you can only access \"localhost\" routes on the server on which you are running minecraft). This route should show you basic information about your server, like the motd and player count.  # Additional data Certain endpoints (such as `/player`, `/entity` and `/tile-entity` have additional properties which are not documented here, because the data depends on the concrete object type (eg. `Sheep` have a wool color, others do not) and on the other plugins/mods that are running on your server which might add additional data.  You can also find more information in the github docs (https:/github.com/Valandur/Web-API/tree/master/docs/DATA.md) 
 *
 * OpenAPI spec version: <version>
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// CommandRequest
    /// </summary>
    [DataContract]
    public partial class CommandRequest :  IEquatable<CommandRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CommandRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CommandRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CommandRequest" /> class.
        /// </summary>
        /// <param name="Name">The name that is displayed as the executor. (default to &quot;Web-API&quot;).</param>
        /// <param name="Command">The command and it&#39;s arguments that are sent to the server. (required).</param>
        /// <param name="WaitLines">The minimum amount of lines of text to wait for before returning the response..</param>
        /// <param name="WaitTime">The amount of time in milliseconds to wait for response messages from the server..</param>
        public CommandRequest(string Name = "Web-API", string Command = default(string), decimal? WaitLines = default(decimal?), decimal? WaitTime = default(decimal?))
        {
            // to ensure "Command" is required (not null)
            if (Command == null)
            {
                throw new InvalidDataException("Command is a required property for CommandRequest and cannot be null");
            }
            else
            {
                this.Command = Command;
            }
            // use default value if no "Name" provided
            if (Name == null)
            {
                this.Name = "Web-API";
            }
            else
            {
                this.Name = Name;
            }
            this.WaitLines = WaitLines;
            this.WaitTime = WaitTime;
        }
        
        /// <summary>
        /// The name that is displayed as the executor.
        /// </summary>
        /// <value>The name that is displayed as the executor.</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// The command and it&#39;s arguments that are sent to the server.
        /// </summary>
        /// <value>The command and it&#39;s arguments that are sent to the server.</value>
        [DataMember(Name="command", EmitDefaultValue=false)]
        public string Command { get; set; }

        /// <summary>
        /// The minimum amount of lines of text to wait for before returning the response.
        /// </summary>
        /// <value>The minimum amount of lines of text to wait for before returning the response.</value>
        [DataMember(Name="waitLines", EmitDefaultValue=false)]
        public decimal? WaitLines { get; set; }

        /// <summary>
        /// The amount of time in milliseconds to wait for response messages from the server.
        /// </summary>
        /// <value>The amount of time in milliseconds to wait for response messages from the server.</value>
        [DataMember(Name="waitTime", EmitDefaultValue=false)]
        public decimal? WaitTime { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CommandRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Command: ").Append(Command).Append("\n");
            sb.Append("  WaitLines: ").Append(WaitLines).Append("\n");
            sb.Append("  WaitTime: ").Append(WaitTime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as CommandRequest);
        }

        /// <summary>
        /// Returns true if CommandRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of CommandRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CommandRequest other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.Command == other.Command ||
                    this.Command != null &&
                    this.Command.Equals(other.Command)
                ) && 
                (
                    this.WaitLines == other.WaitLines ||
                    this.WaitLines != null &&
                    this.WaitLines.Equals(other.WaitLines)
                ) && 
                (
                    this.WaitTime == other.WaitTime ||
                    this.WaitTime != null &&
                    this.WaitTime.Equals(other.WaitTime)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                if (this.Command != null)
                    hash = hash * 59 + this.Command.GetHashCode();
                if (this.WaitLines != null)
                    hash = hash * 59 + this.WaitLines.GetHashCode();
                if (this.WaitTime != null)
                    hash = hash * 59 + this.WaitTime.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
