/* 
 * WebAPI
 *
 * Access Sponge powered Minecraft servers through a WebAPI  # Introduction This is the documentation of the various API routes offered by the WebAPI plugin.  This documentation assumes that you are familiar with the basic concepts of Web API's, such as `GET`, `PUT`, `POST` and `DELETE` methods, request `HEADERS` and `RESPONSE CODES` and `JSON` data.  By default this documentation can be found at http:/localhost:8080 (while your minecraft server is running) and the various routes start with http:/localhost:8080/api/...  As a quick test try reaching the route http:/localhost:8080/api/info (remember that you can only access \"localhost\" routes on the server on which you are running minecraft). This route should show you basic information about your server, like the motd and player count.  # Additional data Certain endpoints (such as `/player`, `/entity` and `/tile-entity` have additional properties which are not documented here, because the data depends on the concrete object type (eg. `Sheep` have a wool color, others do not) and on the other plugins/mods that are running on your server which might add additional data.  You can also find more information in the github docs (https:/github.com/Valandur/Web-API/tree/master/docs/DATA.md) 
 *
 * OpenAPI spec version: <version>
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// NationsRect
    /// </summary>
    [DataContract]
    public partial class NationsRect :  IEquatable<NationsRect>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NationsRect" /> class.
        /// </summary>
        /// <param name="World">World.</param>
        /// <param name="MinX">The minimum x coordinate of this rect..</param>
        /// <param name="MinY">The minimum y coordinate of this rect..</param>
        /// <param name="MaxX">The maximum x coordinate of this rect..</param>
        /// <param name="MaxY">The maximum y coordinate of this rect..</param>
        public NationsRect(World World = default(World), decimal? MinX = default(decimal?), decimal? MinY = default(decimal?), decimal? MaxX = default(decimal?), decimal? MaxY = default(decimal?))
        {
            this.World = World;
            this.MinX = MinX;
            this.MinY = MinY;
            this.MaxX = MaxX;
            this.MaxY = MaxY;
        }
        
        /// <summary>
        /// Gets or Sets World
        /// </summary>
        [DataMember(Name="world", EmitDefaultValue=false)]
        public World World { get; set; }

        /// <summary>
        /// The minimum x coordinate of this rect.
        /// </summary>
        /// <value>The minimum x coordinate of this rect.</value>
        [DataMember(Name="minX", EmitDefaultValue=false)]
        public decimal? MinX { get; set; }

        /// <summary>
        /// The minimum y coordinate of this rect.
        /// </summary>
        /// <value>The minimum y coordinate of this rect.</value>
        [DataMember(Name="minY", EmitDefaultValue=false)]
        public decimal? MinY { get; set; }

        /// <summary>
        /// The maximum x coordinate of this rect.
        /// </summary>
        /// <value>The maximum x coordinate of this rect.</value>
        [DataMember(Name="maxX", EmitDefaultValue=false)]
        public decimal? MaxX { get; set; }

        /// <summary>
        /// The maximum y coordinate of this rect.
        /// </summary>
        /// <value>The maximum y coordinate of this rect.</value>
        [DataMember(Name="maxY", EmitDefaultValue=false)]
        public decimal? MaxY { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NationsRect {\n");
            sb.Append("  World: ").Append(World).Append("\n");
            sb.Append("  MinX: ").Append(MinX).Append("\n");
            sb.Append("  MinY: ").Append(MinY).Append("\n");
            sb.Append("  MaxX: ").Append(MaxX).Append("\n");
            sb.Append("  MaxY: ").Append(MaxY).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as NationsRect);
        }

        /// <summary>
        /// Returns true if NationsRect instances are equal
        /// </summary>
        /// <param name="other">Instance of NationsRect to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NationsRect other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.World == other.World ||
                    this.World != null &&
                    this.World.Equals(other.World)
                ) && 
                (
                    this.MinX == other.MinX ||
                    this.MinX != null &&
                    this.MinX.Equals(other.MinX)
                ) && 
                (
                    this.MinY == other.MinY ||
                    this.MinY != null &&
                    this.MinY.Equals(other.MinY)
                ) && 
                (
                    this.MaxX == other.MaxX ||
                    this.MaxX != null &&
                    this.MaxX.Equals(other.MaxX)
                ) && 
                (
                    this.MaxY == other.MaxY ||
                    this.MaxY != null &&
                    this.MaxY.Equals(other.MaxY)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.World != null)
                    hash = hash * 59 + this.World.GetHashCode();
                if (this.MinX != null)
                    hash = hash * 59 + this.MinX.GetHashCode();
                if (this.MinY != null)
                    hash = hash * 59 + this.MinY.GetHashCode();
                if (this.MaxX != null)
                    hash = hash * 59 + this.MaxX.GetHashCode();
                if (this.MaxY != null)
                    hash = hash * 59 + this.MaxY.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
