/* 
 * WebAPI
 *
 * Access Sponge powered Minecraft servers through a WebAPI  # Introduction This is the documentation of the various API routes offered by the WebAPI plugin.  This documentation assumes that you are familiar with the basic concepts of Web API's, such as `GET`, `PUT`, `POST` and `DELETE` methods, request `HEADERS` and `RESPONSE CODES` and `JSON` data.  By default this documentation can be found at http:/localhost:8080 (while your minecraft server is running) and the various routes start with http:/localhost:8080/api/...  As a quick test try reaching the route http:/localhost:8080/api/info (remember that you can only access \"localhost\" routes on the server on which you are running minecraft). This route should show you basic information about your server, like the motd and player count.  # Additional data Certain endpoints (such as `/player`, `/entity` and `/tile-entity` have additional properties which are not documented here, because the data depends on the concrete object type (eg. `Sheep` have a wool color, others do not) and on the other plugins/mods that are running on your server which might add additional data.  You can also find more information in the github docs (https:/github.com/Valandur/Web-API/tree/master/docs/DATA.md) 
 *
 * OpenAPI spec version: <version>
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// NucleusKitFull
    /// </summary>
    [DataContract]
    public partial class NucleusKitFull :  IEquatable<NucleusKitFull>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NucleusKitFull" /> class.
        /// </summary>
        /// <param name="Name">The name of the kit..</param>
        /// <param name="Cost">The cost to buy this kit..</param>
        /// <param name="Cooldown">The cooldown for this kit in milliseconds..</param>
        /// <param name="FirstJoinKit">True if players receive this kit when joining the server for the first time, false otherwise..</param>
        /// <param name="OneTime">True if this kit can only be received one, false otherwise..</param>
        /// <param name="Commands">The commands that are executed for the player when receiving this kit..</param>
        /// <param name="Stacks">The items that the player receives when aquiring this kit..</param>
        public NucleusKitFull(string Name = default(string), double? Cost = default(double?), decimal? Cooldown = default(decimal?), bool? FirstJoinKit = default(bool?), bool? OneTime = default(bool?), List<string> Commands = default(List<string>), List<ItemStack> Stacks = default(List<ItemStack>))
        {
            this.Name = Name;
            this.Cost = Cost;
            this.Cooldown = Cooldown;
            this.FirstJoinKit = FirstJoinKit;
            this.OneTime = OneTime;
            this.Commands = Commands;
            this.Stacks = Stacks;
        }
        
        /// <summary>
        /// The name of the kit.
        /// </summary>
        /// <value>The name of the kit.</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// The cost to buy this kit.
        /// </summary>
        /// <value>The cost to buy this kit.</value>
        [DataMember(Name="cost", EmitDefaultValue=false)]
        public double? Cost { get; set; }

        /// <summary>
        /// The cooldown for this kit in milliseconds.
        /// </summary>
        /// <value>The cooldown for this kit in milliseconds.</value>
        [DataMember(Name="cooldown", EmitDefaultValue=false)]
        public decimal? Cooldown { get; set; }

        /// <summary>
        /// True if players receive this kit when joining the server for the first time, false otherwise.
        /// </summary>
        /// <value>True if players receive this kit when joining the server for the first time, false otherwise.</value>
        [DataMember(Name="firstJoinKit", EmitDefaultValue=false)]
        public bool? FirstJoinKit { get; set; }

        /// <summary>
        /// True if this kit can only be received one, false otherwise.
        /// </summary>
        /// <value>True if this kit can only be received one, false otherwise.</value>
        [DataMember(Name="oneTime", EmitDefaultValue=false)]
        public bool? OneTime { get; set; }

        /// <summary>
        /// The commands that are executed for the player when receiving this kit.
        /// </summary>
        /// <value>The commands that are executed for the player when receiving this kit.</value>
        [DataMember(Name="commands", EmitDefaultValue=false)]
        public List<string> Commands { get; set; }

        /// <summary>
        /// The items that the player receives when aquiring this kit.
        /// </summary>
        /// <value>The items that the player receives when aquiring this kit.</value>
        [DataMember(Name="stacks", EmitDefaultValue=false)]
        public List<ItemStack> Stacks { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NucleusKitFull {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Cost: ").Append(Cost).Append("\n");
            sb.Append("  Cooldown: ").Append(Cooldown).Append("\n");
            sb.Append("  FirstJoinKit: ").Append(FirstJoinKit).Append("\n");
            sb.Append("  OneTime: ").Append(OneTime).Append("\n");
            sb.Append("  Commands: ").Append(Commands).Append("\n");
            sb.Append("  Stacks: ").Append(Stacks).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as NucleusKitFull);
        }

        /// <summary>
        /// Returns true if NucleusKitFull instances are equal
        /// </summary>
        /// <param name="other">Instance of NucleusKitFull to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NucleusKitFull other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.Cost == other.Cost ||
                    this.Cost != null &&
                    this.Cost.Equals(other.Cost)
                ) && 
                (
                    this.Cooldown == other.Cooldown ||
                    this.Cooldown != null &&
                    this.Cooldown.Equals(other.Cooldown)
                ) && 
                (
                    this.FirstJoinKit == other.FirstJoinKit ||
                    this.FirstJoinKit != null &&
                    this.FirstJoinKit.Equals(other.FirstJoinKit)
                ) && 
                (
                    this.OneTime == other.OneTime ||
                    this.OneTime != null &&
                    this.OneTime.Equals(other.OneTime)
                ) && 
                (
                    this.Commands == other.Commands ||
                    this.Commands != null &&
                    this.Commands.SequenceEqual(other.Commands)
                ) && 
                (
                    this.Stacks == other.Stacks ||
                    this.Stacks != null &&
                    this.Stacks.SequenceEqual(other.Stacks)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                if (this.Cost != null)
                    hash = hash * 59 + this.Cost.GetHashCode();
                if (this.Cooldown != null)
                    hash = hash * 59 + this.Cooldown.GetHashCode();
                if (this.FirstJoinKit != null)
                    hash = hash * 59 + this.FirstJoinKit.GetHashCode();
                if (this.OneTime != null)
                    hash = hash * 59 + this.OneTime.GetHashCode();
                if (this.Commands != null)
                    hash = hash * 59 + this.Commands.GetHashCode();
                if (this.Stacks != null)
                    hash = hash * 59 + this.Stacks.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
